### ISSUE TITLE
can't find the model 

### ISSUE THREAD

**Issue by 14790897** [ashishpatel26/LLM-Finetuning#2]
https://github.com/ashishpatel26/LLM-Finetuning/blob/fb688035920696599d53f283899629bfd39f09e9/14.Finetuning_Mistral_7b_Using_AutoTrain.ipynb#L2761

```
OSError: bn22/Mistral-7B-Instruct-v0.1-sharded is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models' If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```

**Comment by Tilemachoc** [comment]
I believe the issue may stem from the **"bn22/Mistral-7B-Instruct-v0.1-sharded"** model not being publicly available on Hugging Face or it being private and lacking the necessary access token for AutoTrainer.

To check if the model is private and you have access (assuming you have access to the "bn22" Hugging Face account), try visiting these links:

**Model Link**: https://huggingface.co/bn22/Mistral-7B-Instruct-v0.1-sharded - If there's no 404 Error, it suggests the model is private and you have access.
**Profile Link**: https://huggingface.co/bn22 - If you see the model "Mistral-7B-Instruct-v0.1-sharded" listed here, it indicates private access.
If you have access to the model:

Generate a token at [Hugging Face Tokens](https://huggingface.co/settings/tokens).
Modify your command to include the token:

`"!autotrain llm --train --project_name mistral-7b-mj-finetuned --model bn22/Mistral-7B-Instruct-v0.1-sharded --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft --target_modules q_proj,v_proj --push_to_hub --repo_id ashishpatel26/mistral-7b-mj-finetuned --token <your_token>"
`

If you don't have access to "bn22" but are sure the model is private and exists, you will need to contact the account owner for the token.

In case you cannot access this model or it doesn't exist, consider using an alternative model available on the Hugging Face model hub, such as filipealmeida/Mistral-7B-Instruct-v0.1-sharded. Modify your command accordingly:

`"!autotrain llm --train --project_name mistral-7b-mj-finetuned --model filipealmeida/Mistral-7B-Instruct-v0.1-sharded --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft --target_modules q_proj,v_proj --push_to_hub --repo_id ashishpatel26/mistral-7b-mj-finetuned"
`

**Comment by 14790897** [comment]
Are you AI?

> I believe the issue may stem from the **"bn22/Mistral-7B-Instruct-v0.1-sharded"** model not being publicly available on Hugging Face or it being private and lacking the necessary access token for AutoTrainer.我认为这个问题可能源于 "bn22/Mistral-7B-Instruct-v0.1-sharded "模型在 Hugging Face 上不公开，或者它是私有的，缺乏 AutoTrainer 所需的访问令牌。
> 
> To check if the model is private and you have access (assuming you have access to the "bn22" Hugging Face account), try visiting these links:要检查模型是否为私有且您有访问权限（假设您有 Hugging Face 帐户 "bn22 "的访问权限），请尝试访问这些链接：
> 
> **Model Link**: https://huggingface.co/bn22/Mistral-7B-Instruct-v0.1-sharded - If there's no 404 Error, it suggests the model is private and you have access.模型链接：https://huggingface.co/bn22/Mistral-7B-Instruct-v0.1-sharded - 如果没有出现 404 错误，说明模型是私人的，您有访问权限。 **Profile Link**: https://huggingface.co/bn22 - If you see the model "Mistral-7B-Instruct-v0.1-sharded" listed here, it indicates private access.资料链接：https://huggingface.co/bn22 - 如果您在这里看到 "Mistral-7B-Instruct-v0.1-sharded "模型，则表明您拥有私人访问权限。 If you have access to the model:如果您可以访问模型：
> 
> Generate a token at [Hugging Face Tokens](https://huggingface.co/settings/tokens).在 "拥抱脸代币 "中生成一个代币。 Modify your command to include the token: 修改你的命令以包含令牌：
> 
> `"!autotrain llm --train --project_name mistral-7b-mj-finetuned --model bn22/Mistral-7B-Instruct-v0.1-sharded --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft --target_modules q_proj,v_proj --push_to_hub --repo_id ashishpatel26/mistral-7b-mj-finetuned --token <your_token>" `
> 
> If you don't have access to "bn22" but are sure the model is private and exists, you will need to contact the account owner for the token.如果您无法访问 "bn22"，但确定该模型是私有的且存在，则需要联系账户所有者获取令牌。
> 
> In case you cannot access this model or it doesn't exist, consider using an alternative model available on the Hugging Face model hub, such as filipealmeida/Mistral-7B-Instruct-v0.1-sharded. Modify your command accordingly:如果无法访问该模型或该模型不存在，请考虑使用 Hugging Face 模型集线器上的替代模型，如 filipealmeida/Mistral-7B-Instruct-v0.1-sharded。请相应修改您的命令：
> 
> `"!autotrain llm --train --project_name mistral-7b-mj-finetuned --model filipealmeida/Mistral-7B-Instruct-v0.1-sharded --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft --target_modules q_proj,v_proj --push_to_hub --repo_id ashishpatel26/mistral-7b-mj-finetuned" `

**Comment by 14790897** [comment]
There is a 404 error  https://huggingface.co/bn22/Mistral-7B-Instruct-v0.1-sharded

**Comment by Tilemachoc** [comment]
> There is a 404 error https://huggingface.co/bn22/Mistral-7B-Instruct-v0.1-sharded

That means the model doesn’t exist. Keep in mind that models can be deleted as well. Search for another model, there are a lot of options and change the command to what I suggested, it should work then.
